spring:
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gdy_boke?useUnicode=true&amp&useSSL=false&amp&characterEncoding=UTF-8
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  mail:
    host: smtp.qq.com
    username: 1136262889@qq.com
    password: aurkbhaborcxifca
    properties:
      mail:
        smtp:
         auth: true
         starttls:
          enable: true
          required: true

#fdfs:
#  so-timeout: 1501
#  connect-timeout: 601
#  thumb-image:
#    width: 200
#    height: 200
#  tracker-list:
#    - 192.168.25.133:22122

ftp:
  host: 192.168.25.129
  port: 21
  username: test
  password: test
  filepath: /home/webapps

  # Swagger界面内容配置
swagger:
  title: TMax API接口文档
  description: TMax Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://www.sscai.club
  contact:
    name: niceyoo
    url: https://www.sscai.club
    email: apkdream@163.com




